# Product Goal Contract for agent-harness
# Created: 2026-01-29

product-goal-contract:
  id: "PG-2026-Q1-agent-harness"
  
  value: |
    最終判断以外を AI チームに委譲できる
    - 契約体系で合意を明文化
    - 場とワークフローでプロセスを提供
    - ペルソナ注入と相互監視で判断の質を維持
  
  kill_criteria:
    - "3ヶ月後に「何を判断すべきかわからない」が 50% 超"
    - "契約活用率が 50% 未満"
    - "手戻り率が現状より悪化"
  
  success_metrics:
    - name: "契約活用率"
      target: "80% 以上"
      current: "測定基盤整備済み（S9）"
    - name: "手戻り率"
      target: "10% 以下"
      current: "測定基盤整備済み（S11）"
    - name: "自律度"
      target: "6ヶ月で介入頻度 50% 減"
      current: "測定基盤整備済み（S13）"
  
  hypotheses:
    - id: H1
      statement: "契約体系が手戻りを減らす"
      risk_type: "value"
      confidence: "high"
      status: "validated"
      validated_at: "2026-03-14"
      evidence: "S7-S11 で契約（sprint-goal, slice, insight）が合意を明文化し、手戻りを構造的に減らした"
    - id: H2
      statement: "場の定義がプロセスを明確にする"
      risk_type: "usability"
      confidence: "high"
      status: "validated"
      validated_at: "2026-03-14"
      evidence: "場テンプレート（sprint-planning, review, retro）が召喚条件を明確にし、persona-council 委譲を確実にした"
    - id: H3
      statement: "スキル/ルールで自律度が上がる"
      risk_type: "feasibility"
      confidence: "high"
      status: "validated"
      validated_at: "2026-03-14"
      evidence: "insight, workload-monitor, metrics スキルが自律的な判断・可視化を可能にした"
  
  stakeholders:
    - name: "Yuki（メンテナー）"
      role: "approver"
      commitment: "このビジョンで agent-harness を作る"
      committed_at: "2026-01-29"
    - name: "コントリビューター"
      role: "reviewer"
      commitment: "このビジョンに沿って貢献する"
      committed_at: null
    - name: "ユーザー"
      role: "informed"
      commitment: "このビジョンを理解して使う"
      committed_at: null
  
  iteration:
    planned: 15  # Q1 で 15 スプリント実施
    current: 15  # S15 完了
    trigger: "仮説の検証結果により方向転換が必要な場合"
  quarterly_report: "research/quarterly/Q1-2026-report.md"
  
  created_at: "2026-01-29"
  updated_at: "2026-01-29"
